### ISSUE TITLE
Can't connect: 

### ISSUE THREAD

**Issue by netrin** [leapcode/bitmask_android#173]
Deprecated TLS cipher name 'DHE-RSA-AES128-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-128-CBC-SHA'

Error: command '223 interface fwmark uid add tun1 0 99999' failed with '400 223 Failed to add uid rule (Invalid argument)'

**Comment by parmegv** [comment]
OK, I've fixed this and some other bugs. Can you test 0.9.0RC1? It's at https://dl.bitmask.net/client/android/Bitmask-Android-0.9.0RC1.apk, and also in the Beta testing section of the Play Store.

**Comment by netrin** [comment]
Hi parmegv, I've tested the 0.9.0RC1 and as far as I can tell, I am encountering the same issues described previously. Status progresses like this: authenticating -> getting client configuration -> assigning IP address xxxxx -> not running! connection not secure! . Then I am unable to log out, the program cannot be
terminated, and external connections through all programs are not possible until the phone is rebooted.

To clarify, I am running a rooted Android 4.4.2 (AT&T Samsung Galaxy S5) and before testing this RC was using the most current version from the Google Play Store.

Perhaps this problem is specific to my phone or configuration? I have been disabling unneeded applications to free up RAM and have experienced no problems running other apps, but could there be a package that Bitmask absolutely requires in order to run properly? Just thinking if I might have disabled a dependency somehow, but I don't know.

Abridged log file:

Deprecated TLS cipher name 'DHE-RSA-AES128-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-128-CBC-SHA'
Protecting socket fd 4
Failed to open the tun interface
Error: command '1715 interface fwmark uid add tun1 0 99999' failed with '400 1715 Failed to add uid rule (Invalid argument)'
ERROR: Cannot open TUN
Process exited with exit value 1

**Comment by parmegv** [comment]
Hi netrin!

 Please, tell bitmask to switch providers and ley me know if that helps.

 If it doesn't, uninstall and install again.

El 2 de enero de 2015 23:02:45 CET, netrin <notifications@github.com> escribió:
>Hi parmegv, I've tested the 0.9.0RC1 and as far as I can tell, I am
>encountering the same issues described previously. Status progresses
>like this: authenticating -> getting client configuration -> assigning
>IP address xxxxx -> not running! connection not secure! . Then I am
>unable to log out, the program cannot be
>terminated, and external connections through all programs are not
>possible until the phone is rebooted.
>
>To clarify, I am running a rooted Android 4.4.2 (AT&T Samsung Galaxy
>S5) and before testing this RC was using the most current version from
>the Google Play Store.
>
>Perhaps this problem is specific to my phone or configuration? I have
>been disabling unneeded applications to free up RAM and have
>experienced no problems running other apps, but could there be a
>package that Bitmask absolutely requires in order to run properly? Just
>thinking if I might have disabled a dependency somehow, but I don't
>know.
>
>Abridged log file:
>
>Deprecated TLS cipher name 'DHE-RSA-AES128-SHA', please use IANA name
>'TLS-DHE-RSA-WITH-AES-128-CBC-SHA'
>Protecting socket fd 4
>Failed to open the tun interface
>Error: command '1715 interface fwmark uid add tun1 0 99999' failed with
>'400 1715 Failed to add uid rule (Invalid argument)'
>ERROR: Cannot open TUN
>Process exited with exit value 1
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/leapcode/bitmask_android/issues/173#issuecomment-68566773

-- 
Enviado desde mi teléfono con K-9 Mail.

**Comment by havoc88** [comment]
Hello guys, I still have this problem. The tun device is not created.
I've tried with the google play version, with the latest on the repository and finally also with the testin 112.
Same problem.

Galaxy S4 original rom

**Comment by netrin** [comment]
Hi parmegv and other kind folks. Sorry for the delay. I did as you instructed and switched providers/reinstalled, but still, no success.

Recently I chose to do a factory reset on my phone for unrelated reasons, and installing and testing Bitmask was one of the first things I did after regaining access to my Google account. Unfortunately, I had the exact same problem with Bitmask after the factory reset!

This strongly suggests to me that the problem actually does lie with Bitmask and not with my phone, which at this point of testing, is a factory-default AT&T Samsung Galaxy S5 G900A un-rooted with all stock applications. Hope this is helpful to you.

**Comment by bitcoinland** [comment]
Hi guys, I am experiencing the exact same problems @netrin describe on https://github.com/leapcode/bitmask_android/issues/173#issuecomment-68387116

My phone is a Samsung Galaxy Note 3 using stock firmware (4.4.2). Bitmask  version 0.9.2RC2

I can attach the logs if they are helpful.

**Comment by ChepasJuanetes** [comment]
I experience a similar problem with two physical devices, using the application from the bitmask website.

1. Open bitmask in Android
2. Choose provider (demo.bitmask.net, riseup or calyx)
3. Input user & password and login
4. Press button to establish VPN connection
5. Confirm Android warning

Following message appears: "No process running". After that, android can't use any internet connection until the phone is rebooted. Switch off and on wireless or data connection doesn't work. Trying to "disconnect" from VPN doesn't work either.

Log:

https://www.zerobin.net/?4215e42e7883df7c#vnyH9X24CNblmzI8TmzBNCtmXIltXA080I9qD1cdwA0=

**Comment by cyBerta** [comment]
The issue will be tracked here: https://0xacab.org/leap/bitmask_android/issues/8769.
